#!/usr/bin/python

import wshttpd
import glib

class Reader:
	def __init__ (self, socket):
		pass
	def quit (self):
		wshttpd.endloop ()

c = wshttpd.RPCWebsocket (8000, Reader, tls = None)

# Use an idle handler, because endloop must not be called before fgloop.
def later ():
	print c.a ()
glib.idle_add (later)

wshttpd.fgloop ()
