#!/usr/bin/python

import wshttpd

class Reader:
	def __init__ (self, socket):
		pass
	def quit (self):
		wshttpd.endloop ()

c = wshttpd.RPCWebsocket (8000, Reader, tls = None)
print c.a ()

wshttpd.fgloop ()
