#!/usr/bin/python

import websockets
import glib

class Reader:
	def __init__ (self, socket):
		pass
	def quit (self):
		websockets.endloop ()

c = websockets.RPC (8000, Reader)

# Use an idle handler, because endloop must not be called before fgloop.
def later ():
	print c.a ()
glib.idle_add (later)

websockets.fgloop ()
